### PR TITLE
review algo phase 1

### PR DESCRIPTION
**Pull request by michaelmera**
Here is my review for the code corresponding to the algorithm of phase 1 in the paper. I found just one mistake when comparing with the paper and it doesn't impact the functionality, but there were a few things that were really confusing, so I refactored that into a PR. Hopefully it should now more closely match what can be seen in the paper.

I tried to explain the motivation of each refactoring in the commit messages.

I think `get_candidates` matches the paper but I only glanced at it. So if you want to do your own review afterwards, it might be a good place to start.

### CODE REVIEW

**Comment by bendrissou** [comment]
I am afraid I don't agree with the mistake you pointed out. For "P alpha Q" candidate, I think the authors meant that the regex PaQ should be considered at each generalization step. Annotating alpha with a rep tag or an alt tag doesn't affect the regex. The tags are there to denote future generalizations only. Also please check steps R2 and R5 in Figure 2. There you can see that the last candidate is annotated with a rep tag.

**Comment by michaelmera** [comment]
> I am afraid I don't agree with the mistake you pointed out. For "P alpha Q" candidate, I think the authors meant that the regex PaQ should be considered at each generalization step. Annotating alpha with a rep tag or an alt tag doesn't affect the regex. The tags are there to denote future generalizations only. Also please check steps R2 and R5 in Figure 2. There you can see that the last candidate is annotated with a rep tag.

I see... This is indeed confusing, I didn't consider the example in Figure 2 but only the actual rules in the paper. And the rules in section 4.1 are quite clear about what can be generated in each generalization step: for "P alpha_alt Q" (which are handled by `gen_alt`), it should be the "P (alpha1_rep + alpha2_alt) Q" with alpha1 alpha2 non empty. Additionally, "the candidate P alpha Q is also generated". So I really don't see any reason to add "P alpha_rep Q".

Now, you're right regarding the example in Figure 2, I totally agree with you that it doesn't match what is written in section 4.1. So I can only understand that as an error from the author.

I also agree that generating "P alpha_rep Q" doesn't change the regex, but it's still not what is in the paper, and I think you should stick closely to what is written.

Anyway, feel free to remove this particular commit from the PR (or really any commit you don't agree with).

**Comment by vrthra** [comment]
Actually, I think that this observation a good _comment_ to add in the code pointing out the inconsistency between the figure and the text. This lends more credence to our code, showing that we have done our homework.

**Comment by bendrissou** [comment]
> > I am afraid I don't agree with the mistake you pointed out. For "P alpha Q" candidate, I think the authors meant that the regex PaQ should be considered at each generalization step. Annotating alpha with a rep tag or an alt tag doesn't affect the regex. The tags are there to denote future generalizations only. Also please check steps R2 and R5 in Figure 2. There you can see that the last candidate is annotated with a rep tag.
> 
> I see... This is indeed confusing, I didn't consider the example in Figure 2 but only the actual rules in the paper. And the rules in section 4.1 are quite clear about what can be generated in each generalization step: for "P alpha_alt Q" (which are handled by `gen_alt`), it should be the "P (alpha1_rep + alpha2_alt) Q" with alpha1 alpha2 non empty. Additionally, "the candidate P alpha Q is also generated". So I really don't see any reason to add "P alpha_rep Q".
> 
> Now, you're right regarding the example in Figure 2, I totally agree with you that it doesn't match what is written in section 4.1. So I can only understand that as an error from the author.
> 
> I also agree that generating "P alpha_rep Q" doesn't change the regex, but it's still not what is in the paper, and I think you should stick closely to what is written.
> 
> Anyway, feel free to remove this particular commit from the PR (or really any commit you don't agree with).

Yes I agree that we should follow the algorithm, such as assigning the right tags.

However, there are ambiguities and inconsistencies in the paper to say the least. When in doubts, I always resort to the XML example given in Figure 2. 

For example, consider step R8 in figure 2.  When generalizing [h]_rep ,the result was a single candidate "h". But if we follow the algorithm description we should get ([h]_alt)*

**Review by bendrissou — COMMENTED** [review]
I approve all commits, except commit a7e553a "fix wrong last candidate in gen_alt".

**Comment by vrthra** [comment]
I will merge this, then revert `a7e553a` because I don't know how to pick and remove specific comments from a PR.

**Pull request merged**
