### PR TITLE
Review algo character generalization

### PR DESCRIPTION
**Pull request by michaelmera**
I reviewed the Character Generalization part. The code was really difficult to understand so I propose in this PR refactoring changes that should make it easier to grasp and verify for a reviewer. It's not perfect, far from it in fact, but at least one can make some sense out of it.

I based this PR on the branch with the changes of the PR for the phase 1 review, so this include those commits. The new commits start at 18b4d24.

### CODE REVIEW

**Comment by bendrissou** [comment]
For commit 7f63a0a, I couldn't understand why you deleted statement _**self.newly_generalized = False**_ in lines 21, 39.

My intent was to mark the regex as part of context once it is checked/tested. The checks happen both in Phase 1 and in character generalization phase.

**Comment by vrthra** [comment]
@michaelmera I have merged the other PR, could you please pull and update this PR? it would be easier to inspect the changes then.

**Comment by michaelmera** [comment]
> For commit [7f63a0a](https://github.com/vrthra/PyGlade/commit/7f63a0afedb9dbc5e920fc4d32ebf05cc175dbf0), I couldn't understand why you deleted statement _**self.newly_generalized = False**_ in lines 21, 39.
> 
> My intent was to mark the regex as part of context once it is checked/tested. The checks happen both in Phase 1 and in character generalization phase.

You're right. I didn't realize that it was used in this way in Phase 1. I've introduced a new commit reverting this change.

**Review by bendrissou — APPROVED** [review]
Approved. Thank you.

**Comment by bendrissou** [comment]
@michaelmera please have another look at _**gen_char()**_ function. I don't understand why you added statement _**regex.newly_generalized = False**_ at lines 223, 227. Also there is an unnecessary line 235.

**Comment by bendrissou** [comment]
> @michaelmera please have another look at _**gen_char()**_ function. I don't understand why you added statement _**regex.newly_generalized = False**_ at lines 223, 227. Also there is an unnecessary line 235.

Ok, I have fixed that in a new commit.

**Comment by michaelmera** [comment]
> > @michaelmera please have another look at _**gen_char()**_ function. I don't understand why you added statement _**regex.newly_generalized = False**_ at lines 223, 227. Also there is an unnecessary line 235.
> 
> Ok, I have fixed that in a new commit.

Yes, these lines should be unnecessary now. Good catch.

**Pull request merged**
